from typing import Any, AsyncGenerator
from typing_extensions import override

from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event
from google.adk.tools import ToolContext
from pydantic import BaseModel, Field, field_validator, model_validator

from src.logger import logger
from src.agents.experts.base import CreativeExpert
from src.agents.experts.image_editing import tool as editing_tools
from src.agents.experts.schema_utils import as_prompt_list, clean_string, current_output_dict
from src.runtime.workspace import build_workspace_file_record, save_binary_output


class ImageEditingParameters(BaseModel):
    """Structured request contract read from ``current_parameters``."""

    raw_input_paths: Any = None
    prompt_list: list[str] = Field(default_factory=list)
    provider: str = "nano_banana"
    has_prompt_key: bool = False

    @model_validator(mode="before")
    @classmethod
    def _coerce_mapping(cls, value: Any) -> dict[str, Any]:
        if not isinstance(value, dict):
            return {}
        return {
            "raw_input_paths": value.get("input_paths", value.get("input_path")),
            "prompt_list": value.get("prompt"),
            "provider": value.get("provider", "nano_banana"),
            "has_prompt_key": "prompt" in value,
        }

    @field_validator("prompt_list", mode="before")
    @classmethod
    def _normalize_prompt_list(cls, value: Any) -> list[str]:
        return as_prompt_list(value)

    @field_validator("provider", mode="before")
    @classmethod
    def _strip_provider(cls, value: Any) -> str:
        return clean_string(value)

    @field_validator("provider")
    @classmethod
    def _normalize_provider(cls, value: str) -> str:
        return value.lower() or "nano_banana"

    @property
    def missing_required_fields(self) -> bool:
        """Whether the existing image-edit request lacks required parameters."""
        return self.raw_input_paths is None or not self.has_prompt_key


class ImageEditingOutput(BaseModel):
    """Structured ``current_output`` contract emitted by ``ImageEditingAgent``."""

    status: str
    message: str
    output_files: list[dict[str, Any]] | None = None

    @field_validator("status", mode="before")
    @classmethod
    def _normalize_status(cls, value: Any) -> str:
        return clean_string(value).lower() or "error"

    @field_validator("message", mode="before")
    @classmethod
    def _strip_message(cls, value: Any) -> str:
        return clean_string(value)

    def to_current_output(self) -> dict[str, Any]:
        """Return the stable dictionary payload stored in ADK session state."""
        return current_output_dict(self)


class ImageEditingAgent(CreativeExpert):
    """A custom agent that orchestrates a sequence of agents to generate an image from text."""

    def __init__(
        self,
        name: str,
        description: str = "",
    ) -> None:
        """Initializes the ImageEditingAgent."""

        super().__init__(
            name=name,
            description=description
        )

    @override
    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """Runs the ImageEditingAgent asynchronously.

        This method orchestrates the sequence of agents to generate an image from text.

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image editing process.
        """
        raw_parameters = ctx.session.state.get('current_parameters', {})
        current_parameters = ImageEditingParameters.model_validate(raw_parameters)

        if current_parameters.missing_required_fields:
            error_text = f"Missing parameters for {self.name}. Required fields: input_path or input_paths, prompt"
            current_output = ImageEditingOutput(status="error", message=error_text).to_current_output()
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output":current_output}) 
            return

        input_paths = current_parameters.raw_input_paths
        prompt_list = current_parameters.prompt_list
        provider = current_parameters.provider

        if provider == "seedream":
            rsp = await editing_tools.seedream_image_edit_tool(ToolContext(ctx), prompt_list)
        else:
            rsp = await editing_tools.nano_banana_image_edit_tool(ToolContext(ctx), prompt_list)
        current_turn = int(ctx.session.state.get("turn_index", 0) or 0)
        current_step = int(ctx.session.state.get("step", 0) or 0)
        current_expert_step = int(ctx.session.state.get("expert_step", 0) or 0)

        if rsp["status"] == "error":
            error_text = f"turn {current_turn}, step {current_step}: {self.name} execution failed: {rsp['message']}"
            current_output = ImageEditingOutput(status="error", message=error_text).to_current_output()

            logger.error(error_text)
            yield self.format_event(error_text, {"current_output":current_output}) 
            return
        
        else:
            # save artifact
            text = f"Turn {current_turn}, step {current_step}: {self.name} finished editing {len(prompt_list)} image(s)."
            output_artifacts = []

            for i,(prompt, message) in enumerate(zip(prompt_list, rsp['message'])):
                if not message:
                    text += f"\nImage {i+1} editing failed. Prompt: {prompt}."
                    continue

                output_path = save_binary_output(
                    message,
                    session_id=ctx.session.id,
                    turn_index=current_turn,
                    step=current_step,
                    output_type="editing",
                    index=i,
                    extension=".png",
                )
                artifact_name = output_path.name

                text += f"\nImage {i+1} editing succeeded. Output file: {artifact_name}"
                description = (
                    f"new image edited based on the original workspace files: "
                    f"{input_paths}, the editing instruction is: {prompt}"
                )
                
                output_artifacts.append(
                    build_workspace_file_record(
                        output_path,
                        description=description,
                        source="expert",
                        name=artifact_name,
                        turn=current_turn,
                        step=current_step,
                        expert_step=current_expert_step,
                    )
                )

            if not output_artifacts:
                error_text = (
                    f"turn {current_turn}, step {current_step}: "
                    f"{self.name} execution failed: all edited images were empty."
                )
                current_output = ImageEditingOutput(status="error", message=error_text).to_current_output()
                logger.error(error_text)
                yield self.format_event(error_text, {"current_output": current_output})
                return

            # output event
            current_output = ImageEditingOutput(
                status="success",
                message=text,
                output_files=output_artifacts,
            ).to_current_output()
            yield self.format_event(text, {'current_output':current_output})
            return


__all__ = [
    "ImageEditingAgent",
    "ImageEditingOutput",
    "ImageEditingParameters",
]
