import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

from google.adk.artifacts import InMemoryArtifactService
from google.adk.sessions import InMemorySessionService

from src.agents.experts.code_generation import CodeGenerationExpert
from src.agents.orchestrator.orchestrator_agent import Orchestrator
from src.runtime.workspace import build_workspace_file_record, workspace_relative_path, workspace_root


class DesignProductToolTests(unittest.IsolatedAsyncioTestCase):
    def test_orchestrator_exposes_design_product_tool(self) -> None:
        orchestrator = Orchestrator(
            session_service=InMemorySessionService(),
            artifact_service=InMemoryArtifactService(),
            expert_agents={},
        )

        tool_names = {getattr(tool, "__name__", "") for tool in orchestrator.agent.tools}

        self.assertIn("run_design_product", tool_names)
        self.assertIn("run_design_product", orchestrator._build_instruction())

    async def test_run_design_product_returns_questions_without_generation(self) -> None:
        orchestrator = Orchestrator(
            session_service=InMemorySessionService(),
            artifact_service=InMemoryArtifactService(),
            expert_agents={"CodeGenerationExpert": CodeGenerationExpert(name="CodeGenerationExpert")},
        )
        tool_context = SimpleNamespace(state={"sid": "design-test", "turn_index": 1, "step": 0, "expert_step": 0})

        with patch("src.agents.orchestrator.orchestrator_agent.dispatch_expert_call") as dispatch:
            result = await orchestrator.run_design_product(
                prompt="做一个后台看板。",
                scenario="dashboard",
                allow_assumptions=False,
                tool_context=tool_context,
            )

        self.assertEqual(result["status"], "needs_clarification")
        self.assertTrue(result["questions"])
        dispatch.assert_not_called()
        self.assertIn("design_product_brief", tool_context.state)

    async def test_run_design_product_calls_code_generation_and_records_output(self) -> None:
        orchestrator = Orchestrator(
            session_service=InMemorySessionService(),
            artifact_service=InMemoryArtifactService(),
            expert_agents={"CodeGenerationExpert": CodeGenerationExpert(name="CodeGenerationExpert")},
        )
        tool_context = SimpleNamespace(state={"sid": "design-test", "turn_index": 1, "step": 0, "expert_step": 0})

        async def _fake_dispatch(**kwargs):
            output_file = workspace_root() / "generated" / "design-test" / "turn1" / "dashboard.html"
            output_file.parent.mkdir(parents=True, exist_ok=True)
            output_file.write_text("<!doctype html><html><body>Dashboard</body></html>\n", encoding="utf-8")
            record = build_workspace_file_record(
                output_file,
                description="Code generated by CodeGenerationExpert (html).",
                source="expert",
                turn=1,
                step=1,
                expert_step=0,
            )
            state = kwargs["tool_context"].state
            state["generated"] = [record]
            state["new_files"] = [record]
            state["files_history"] = [[record]]
            return SimpleNamespace(
                tool_result={
                    "agent_name": "CodeGenerationExpert",
                    "status": "success",
                    "message": "Generated html code.",
                    "output_text": "",
                    "output_files": [record],
                    "structured_data": {},
                    "parameters": {},
                }
            )

        with patch(
            "src.agents.orchestrator.orchestrator_agent.dispatch_expert_call",
            side_effect=_fake_dispatch,
        ) as dispatch:
            result = await orchestrator.run_design_product(
                prompt="设计一个运营数据 dashboard，展示 DAU、转化率、留存和渠道 ROI。",
                scenario="operation_data_ui",
                allow_assumptions=True,
                tool_context=tool_context,
            )

        dispatch.assert_called_once()
        self.assertEqual(result["status"], "success")
        self.assertEqual(result["brief"]["selection"]["surface"], "dashboard")
        self.assertEqual(result["brief"]["selection"]["task_skill"], "dashboard")
        self.assertEqual(result["brief"]["selection"]["design_system"], "linear-app")
        self.assertEqual(len(result["output_files"]), 1)
        self.assertEqual(
            result["output_files"][0]["path"],
            workspace_relative_path(Path(workspace_root()) / "generated" / "design-test" / "turn1" / "dashboard.html"),
        )
        self.assertIn("design_product_result", tool_context.state)
        self.assertEqual(tool_context.state["new_files"][0]["path"], result["output_files"][0]["path"])


if __name__ == "__main__":
    unittest.main()
