"""DesignProductManager-private code generation agent."""

from __future__ import annotations

from typing import Any, AsyncGenerator

from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event
from typing_extensions import override

from src.agents.experts.base import CreativeExpert
from src.runtime.code_artifacts import generate_code_artifact


class DesignCodeGenerationAgent(CreativeExpert):
    """Generate code-backed design artifacts with a design-canvas contract."""

    def __init__(self, name: str = "DesignCodeGenerationAgent", description: str = "") -> None:
        """Initialize the private design code generation agent."""
        super().__init__(name=name, description=description)

    async def run_generation(
        self,
        runtime_context: Any,
        *,
        prompt: str,
        language: str = "html",
        output_path: str = "",
        context_files: list[str] | None = None,
        constraints: list[str] | None = None,
    ) -> dict[str, Any]:
        """Generate one design artifact file through the shared code runtime."""
        clean_prompt = str(prompt or "").strip()
        if not clean_prompt:
            return _build_current_output(
                {
                    "status": "error",
                    "message": f"Missing parameters provided to {self.name}, must include: prompt",
                    "error_type": "invalid_parameters",
                    "retryable": False,
                    "raw_error_summary": "missing prompt",
                    "output_files": [],
                    "language": language,
                }
            )

        result = await generate_code_artifact(
            runtime_context,
            prompt=build_design_code_generation_prompt(clean_prompt),
            language=str(language or "html").strip() or "html",
            output_path=str(output_path or "").strip(),
            context_files=context_files or [],
            constraints=build_design_code_generation_constraints(constraints or []),
            output_type="design_code_generation",
            output_description="Design artifact generated by DesignCodeGenerationAgent.",
            output_source="design_code_generation_agent",
        )
        return _build_current_output(result)

    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Run one design code generation request from ADK session parameters."""
        current_parameters = dict(ctx.session.state.get("current_parameters", {}) or {})
        current_output = await self.run_generation(
            ctx,
            prompt=str(current_parameters.get("prompt", "")).strip(),
            language=str(current_parameters.get("language", "html")).strip() or "html",
            output_path=str(current_parameters.get("output_path", "")).strip(),
            context_files=_as_string_list(current_parameters.get("context_files")),
            constraints=_as_string_list(current_parameters.get("constraints")),
        )
        yield self.format_event(
            current_output.get("message", ""),
            {
                "current_output": current_output,
                "design_code_generation_results": current_output,
            },
        )


def build_design_code_generation_prompt(user_prompt: str) -> str:
    """Return the Claude Design-style generation brief for a design artifact."""
    return "\n".join(
        [
            "# Creative Claw Design Artifact Mode",
            "",
            "You are generating a code-backed design artifact for design review, visual critique, and iterative editing.",
            "Treat the output as a design canvas, not a production application or routed website.",
            "",
            "## Design Medium Posture",
            "- HTML is the tool, not the medium. Act as the right design specialist for the requested deliverable.",
            "- Mobile app and product prototypes: act as an interaction designer. Show real flows, states, transitions, 44px+ hit targets, device artboards, and screen relationships.",
            "- Dashboards and internal tools: act as a systems designer. Information density, scanning hierarchy, tabular numerics, filters, states, and operational clarity are the core visuals.",
            "- Landing pages and marketing sites: act as a brand designer. Build narrative, audience fit, proof, conversion path, and one memorable visual move.",
            "- Posters, cards, editorial pages, and decks: act as a visual communication designer. Composition, typographic rhythm, contrast, and message hierarchy matter most.",
            "- Do not turn every brief into a generic SaaS landing page or routed app shell.",
            "",
            "## Content and Information Architecture First",
            "- Lock the content structure before styling: screens, sections, states, data blocks, and key messages.",
            "- If content is missing, use honest labelled placeholders or clearly illustrative sample data. Do not invent fake proof, fake metrics, fake testimonials, or fake brand claims.",
            "- For design exploration, keep the same content and information architecture across directions so reviewers compare visual language, not different products.",
            "",
            "## Visual Direction Framework",
            "- Choose or reflect one clear visual direction before drawing pixels. Useful directions:",
            "  1. editorial_monocle: print-magazine posture, serif display, off-white paper, hairline borders, one warm accent.",
            "  2. modern_minimal: software-native precision, near-greyscale palette, system type, hairline dividers, restrained cobalt-like accent.",
            "  3. warm_soft: cream canvas, softer radii, gentle depth, serif or soft sans display, one terracotta or warm accent.",
            "  4. tech_utility: dense operational UI, tabular numerics, mono for code/data, compact tables, status language, minimal decoration.",
            "  5. brutalist_experimental: exposed grid, loud type, hard borders, little radius, high contrast, deliberate asymmetry.",
            "- When a selected design system is present in the brief, its tokens win. Use the visual direction as composition posture only when it does not conflict with DESIGN.md.",
            "- If the brief says `为我决定` or leaves style open, pick one direction that fits the medium and audience, then make that choice visible in a compact brief/design-system artboard.",
            "",
            "## Style Exploration and Variants",
            "- When the user asks to explore styles, compare 2-3 differentiated directions by default unless a different count is specified.",
            "- Each direction should have a visible label, short design intent, palette/type/component summary, and the same core screens or sections.",
            "- Variants are not random skins: vary palette, type personality, density, border/radius rules, image strategy, and accent budget while preserving content structure.",
            "- Do not hide variants behind tabs or routing. Put them side by side or in stacked canvas sections so a reviewer can compare them immediately.",
            "",
            "## Multi-Direction Canvas Protocol",
            "- When style exploration is requested or useful, structure the artifact as one compact brief/design-system artboard followed by one visible canvas section per direction.",
            "- Default to 3 directions when the brief asks to explore styles and no count is specified; use 2 directions only when the requested scope is small or time-to-first-result matters.",
            "- Each direction section must reuse the same `SCREENS` or `SECTIONS` list and the same domain data. Reviewers should compare visual systems, not different products.",
            "- Give every direction a stable id, title, subtitle, design intent, and token summary covering palette, typography, density, radius/border model, image strategy, and accent budget.",
            "- Visual directions must differ in more than color. Change at least four of: type personality, layout rhythm, density, border/radius system, image/placeholder treatment, component posture, domain metaphor, and accent usage.",
            "- For mobile app work, show the same phone-sized artboards in every direction. If the requested screen count is high, prioritize the most decision-rich screens and note the omitted secondary screens in the brief artboard.",
            "",
            "## Output Contract",
            "- Generate exactly one complete, standalone HTML file unless the caller explicitly asks for another file type.",
            "- The first screen should be the reviewable design surface, not a marketing landing page explaining the work.",
            "- Present screens, states, and variants as visible artboards on a canvas so reviewers can compare them side by side.",
            "- Use stable section, artboard, and component identifiers; future AI edits must be able to target them reliably.",
            "- Prefer fixed-size artboards for product screens, cards, posters, dashboards, and state explorations.",
            "- Do not hide core screens behind routing, tabs, or simulated app navigation when the task is design exploration.",
            "- Include enough labels and brief notes for a design reviewer to understand each artboard's role.",
            "",
            "## Design Canvas Behavior",
            "- If multiple screens or variants are requested or useful, create a lightweight canvas wrapper with sections and artboards.",
            "- Embed the canvas scaffold inside the generated HTML; do not rely on the host app to provide the design canvas.",
            "- Prefer clear local primitives named `DesignCanvas`, `DCViewport`, `DCSection`, and `DCArtboard`, or equivalent names when the structure is obvious.",
            "- Implement the main canvas as a transform-based world: `translate3d(x, y, 0) scale(scale)` with transform origin at the top-left.",
            "- Support canvas navigation without browser scrollbars: trackpad pinch zoom, two-finger scroll pan, and blank-space drag pan.",
            "- Hide scrollbars on the main canvas and artboard frames; only use internal scrolling when the designed product screen itself requires it.",
            "- Keep all artboards measurable in the document so an outer preview shell can fit the complete board if it needs to.",
            "- If JavaScript is enabled, post `{ type: '__dc_present' }` when the canvas mounts and `{ type: '__dc_zoom', scale }` when zoom changes.",
            "- Listen for `{ type: '__dc_set_zoom', scale }` messages from a host toolbar and zoom around the viewport center.",
            "- For app/mobile work, show multiple phone-sized artboards such as 393x852 or another explicit target device size.",
            "- For web/dashboard work, show desktop and important responsive states as separate artboards when helpful.",
            "- Keep visual variants aligned by information architecture: same content structure, meaningfully different visual language.",
            "- Include a compact brief/design-system artboard when it helps communicate palette, typography, components, or assumptions.",
            "",
            "## Code Organization for Reviewable Design Artifacts",
            "- Prefer named local structures such as `SCREENS`, `VARIANTS`, shared domain data, shared primitives, and variant-specific render functions or components.",
            "- Keep shared content/data outside variant implementations so later AI edits can update copy, screens, or domain objects once.",
            "- Keep each visual direction isolated enough that future edits can target one variant without accidentally changing all variants.",
            "- Use meaningful ids for sections and artboards, for example `brief-card`, `a-home`, `b-home`, or `checkout-empty-state`.",
            "- Include a thumbnail or compact cover composition in the document when practical, so previews communicate the artifact before interaction.",
            "",
            "## Design-Product Scope",
            "- Optimize the artifact for design review, AI critique, and visual iteration rather than production deployment.",
            "- Do not turn a design brief into a full routed app, account system, backend workflow, or generic SaaS landing page unless explicitly requested.",
            "- When showing an app or website concept, expose states as artboards instead of forcing the reviewer to click through the product flow.",
            "",
            "## Quality Self-Check Before Finalizing",
            "- Silently score the artifact across five dimensions, then fix the weakest point before returning the file:",
            "  1. Philosophy: does the visual posture match the chosen direction, medium, and audience?",
            "  2. Hierarchy: does each artboard have one obvious visual priority?",
            "  3. Execution: are spacing, alignment, type scale, contrast, and component states clean?",
            "  4. Specificity: does the copy, data, and UI content belong to this brief instead of a generic template?",
            "  5. Restraint: is there one decisive flourish rather than many competing decorations?",
            "- Avoid AI-slop patterns: aggressive purple gradients, emoji feature icons, generic three-card feature rows, rounded cards with colored left borders, fake metrics, lorem ipsum, and decorative icons beside every heading.",
            "- Use one accent color deliberately. If a design system defines tokens, stay inside that palette unless the user explicitly asks to extend it.",
            "",
            "## Implementation Rules",
            "- Use HTML, CSS, and JavaScript that can run locally in the browser without a backend.",
            "- Use inline SVG, CSS, and semantic HTML where possible; avoid external network assets unless the user provided them.",
            "- Keep interactions lightweight and demonstrative; do not build full production business logic.",
            "- Preserve readability and editability over clever minification or opaque generated code.",
            "- Avoid local absolute paths in the generated document.",
            "",
            "## AI Edit Readiness",
            "- Name major elements and data structures clearly.",
            "- Keep repeated screens/components structured instead of fully copy-pasted when a simple local abstraction improves editability.",
            "- If the prompt includes sketch annotations, screenshots, or image critique, reflect them as design changes, not generic image captions.",
            "",
            "# User Design Brief",
            user_prompt.strip(),
        ]
    )


def build_design_code_generation_constraints(extra_constraints: list[str]) -> list[str]:
    """Return default design code generation constraints plus caller constraints."""
    defaults = [
        "Submit only the complete file contents through the code artifact save tool.",
        "Generate a design artifact, not a production app.",
        "Embed a DesignCanvas/DCViewport-style scaffold for the main design surface.",
        "Use transform-based canvas pan/zoom instead of browser-window scrolling for the main design board.",
        "Hide main canvas and artboard scrollbars unless the designed screen explicitly needs internal scrolling.",
        "Support host zoom synchronization messages: __dc_present, __dc_zoom, and __dc_set_zoom.",
        "Use visible sections/artboards for design states, screens, and variants when applicable.",
        "For style exploration, include a brief/design-system artboard and 2-3 visible direction sections with the same screens/content.",
        "Keep multi-direction variants aligned by information architecture while making the visual systems meaningfully different.",
        "Use named local structures such as SCREENS, VARIANTS, shared domain data, and stable artboard ids.",
        "Keep identifiers stable and human-readable for future AI edits.",
        "Do not include local absolute filesystem paths.",
    ]
    return defaults + [str(item) for item in extra_constraints if str(item).strip()]


def _build_current_output(result: dict[str, Any]) -> dict[str, Any]:
    """Normalize a generation result into the private agent output contract."""
    message = str(result.get("message", "") or "").strip()
    status = str(result.get("status", "error") or "error").strip().lower()
    return {
        "status": status,
        "message": message,
        "output_text": message if status == "success" else "",
        "output_files": list(result.get("output_files") or []),
        "error_type": str(result.get("error_type", "") or "").strip(),
        "retryable": bool(result.get("retryable", False)),
        "raw_error_summary": str(result.get("raw_error_summary", "") or "").strip(),
        "language": str(result.get("language", "") or "").strip(),
        "output_path": str(result.get("output_path", "") or "").strip(),
        "warnings": list(result.get("warnings") or []),
        "provider": str(result.get("provider", "") or "").strip(),
        "model_name": str(result.get("model_name", "") or "").strip(),
    }


def _as_string_list(value: Any) -> list[str]:
    """Normalize a scalar or sequence parameter into a string list."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value] if value.strip() else []
    if isinstance(value, (list, tuple, set)):
        return [str(item) for item in value if str(item).strip()]
    return [str(value)]


__all__ = [
    "DesignCodeGenerationAgent",
    "build_design_code_generation_constraints",
    "build_design_code_generation_prompt",
]
