"""DesignProductManager-private code generation agent."""

from __future__ import annotations

from typing import Any, AsyncGenerator

from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event
from typing_extensions import override

from src.agents.experts.base import CreativeExpert
from src.runtime.code_artifacts import generate_code_artifact


class DesignCodeGenerationAgent(CreativeExpert):
    """Generate code-backed design artifacts with a design-canvas contract."""

    def __init__(self, name: str = "DesignCodeGenerationAgent", description: str = "") -> None:
        """Initialize the private design code generation agent."""
        super().__init__(name=name, description=description)

    async def run_generation(
        self,
        runtime_context: Any,
        *,
        prompt: str,
        language: str = "html",
        output_path: str = "",
        context_files: list[str] | None = None,
        constraints: list[str] | None = None,
    ) -> dict[str, Any]:
        """Generate one design artifact file through the shared code runtime."""
        clean_prompt = str(prompt or "").strip()
        if not clean_prompt:
            return _build_current_output(
                {
                    "status": "error",
                    "message": f"Missing parameters provided to {self.name}, must include: prompt",
                    "error_type": "invalid_parameters",
                    "retryable": False,
                    "raw_error_summary": "missing prompt",
                    "output_files": [],
                    "language": language,
                }
            )

        result = await generate_code_artifact(
            runtime_context,
            prompt=build_design_code_generation_prompt(clean_prompt),
            language=str(language or "html").strip() or "html",
            output_path=str(output_path or "").strip(),
            context_files=context_files or [],
            constraints=build_design_code_generation_constraints(constraints or []),
            output_type="design_code_generation",
            output_description="Design artifact generated by DesignCodeGenerationAgent.",
            output_source="design_code_generation_agent",
        )
        return _build_current_output(result)

    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Run one design code generation request from ADK session parameters."""
        current_parameters = dict(ctx.session.state.get("current_parameters", {}) or {})
        current_output = await self.run_generation(
            ctx,
            prompt=str(current_parameters.get("prompt", "")).strip(),
            language=str(current_parameters.get("language", "html")).strip() or "html",
            output_path=str(current_parameters.get("output_path", "")).strip(),
            context_files=_as_string_list(current_parameters.get("context_files")),
            constraints=_as_string_list(current_parameters.get("constraints")),
        )
        yield self.format_event(
            current_output.get("message", ""),
            {
                "current_output": current_output,
                "design_code_generation_results": current_output,
            },
        )


def build_design_code_generation_prompt(user_prompt: str) -> str:
    """Return the Claude Design-style generation brief for a design artifact."""
    return "\n".join(
        [
            "# Creative Claw Design Artifact Mode",
            "",
            "You are generating a code-backed design artifact for design review, visual critique, and iterative editing.",
            "Treat the output as a design canvas, not a production application or routed website.",
            "",
            "## Output Contract",
            "- Generate exactly one complete, standalone HTML file unless the caller explicitly asks for another file type.",
            "- The first screen should be the reviewable design surface, not a marketing landing page explaining the work.",
            "- Present screens, states, and variants as visible artboards on a canvas so reviewers can compare them side by side.",
            "- Use stable section, artboard, and component identifiers; future AI edits must be able to target them reliably.",
            "- Prefer fixed-size artboards for product screens, cards, posters, dashboards, and state explorations.",
            "- Do not hide core screens behind routing, tabs, or simulated app navigation when the task is design exploration.",
            "- Include enough labels and brief notes for a design reviewer to understand each artboard's role.",
            "",
            "## Design Canvas Behavior",
            "- If multiple screens or variants are requested or useful, create a lightweight canvas wrapper with sections and artboards.",
            "- Embed the canvas scaffold inside the generated HTML; do not rely on the host app to provide the design canvas.",
            "- Prefer clear local primitives named `DesignCanvas`, `DCViewport`, `DCSection`, and `DCArtboard`, or equivalent names when the structure is obvious.",
            "- Implement the main canvas as a transform-based world: `translate3d(x, y, 0) scale(scale)` with transform origin at the top-left.",
            "- Support canvas navigation without browser scrollbars: trackpad pinch zoom, two-finger scroll pan, and blank-space drag pan.",
            "- Hide scrollbars on the main canvas and artboard frames; only use internal scrolling when the designed product screen itself requires it.",
            "- Keep all artboards measurable in the document so an outer preview shell can fit the complete board if it needs to.",
            "- If JavaScript is enabled, post `{ type: '__dc_present' }` when the canvas mounts and `{ type: '__dc_zoom', scale }` when zoom changes.",
            "- Listen for `{ type: '__dc_set_zoom', scale }` messages from a host toolbar and zoom around the viewport center.",
            "- For app/mobile work, show multiple phone-sized artboards such as 393x852 or another explicit target device size.",
            "- For web/dashboard work, show desktop and important responsive states as separate artboards when helpful.",
            "- Keep visual variants aligned by information architecture: same content structure, meaningfully different visual language.",
            "- Include a compact brief/design-system artboard when it helps communicate palette, typography, components, or assumptions.",
            "",
            "## Design-Product Scope",
            "- Optimize the artifact for design review, AI critique, and visual iteration rather than production deployment.",
            "- Do not turn a design brief into a full routed app, account system, backend workflow, or generic SaaS landing page unless explicitly requested.",
            "- When showing an app or website concept, expose states as artboards instead of forcing the reviewer to click through the product flow.",
            "",
            "## Implementation Rules",
            "- Use HTML, CSS, and JavaScript that can run locally in the browser without a backend.",
            "- Use inline SVG, CSS, and semantic HTML where possible; avoid external network assets unless the user provided them.",
            "- Keep interactions lightweight and demonstrative; do not build full production business logic.",
            "- Preserve readability and editability over clever minification or opaque generated code.",
            "- Avoid local absolute paths in the generated document.",
            "",
            "## AI Edit Readiness",
            "- Name major elements and data structures clearly.",
            "- Keep repeated screens/components structured instead of fully copy-pasted when a simple local abstraction improves editability.",
            "- If the prompt includes sketch annotations, screenshots, or image critique, reflect them as design changes, not generic image captions.",
            "",
            "# User Design Brief",
            user_prompt.strip(),
        ]
    )


def build_design_code_generation_constraints(extra_constraints: list[str]) -> list[str]:
    """Return default design code generation constraints plus caller constraints."""
    defaults = [
        "Return only the complete file contents.",
        "Generate a design artifact, not a production app.",
        "Embed a DesignCanvas/DCViewport-style scaffold for the main design surface.",
        "Use transform-based canvas pan/zoom instead of browser-window scrolling for the main design board.",
        "Hide main canvas and artboard scrollbars unless the designed screen explicitly needs internal scrolling.",
        "Support host zoom synchronization messages: __dc_present, __dc_zoom, and __dc_set_zoom.",
        "Use visible sections/artboards for design states, screens, and variants when applicable.",
        "Keep identifiers stable and human-readable for future AI edits.",
        "Do not include local absolute filesystem paths.",
    ]
    return defaults + [str(item) for item in extra_constraints if str(item).strip()]


def _build_current_output(result: dict[str, Any]) -> dict[str, Any]:
    """Normalize a generation result into the private agent output contract."""
    message = str(result.get("message", "") or "").strip()
    status = str(result.get("status", "error") or "error").strip().lower()
    return {
        "status": status,
        "message": message,
        "output_text": message if status == "success" else "",
        "output_files": list(result.get("output_files") or []),
        "error_type": str(result.get("error_type", "") or "").strip(),
        "retryable": bool(result.get("retryable", False)),
        "raw_error_summary": str(result.get("raw_error_summary", "") or "").strip(),
        "language": str(result.get("language", "") or "").strip(),
        "output_path": str(result.get("output_path", "") or "").strip(),
        "warnings": list(result.get("warnings") or []),
        "provider": str(result.get("provider", "") or "").strip(),
        "model_name": str(result.get("model_name", "") or "").strip(),
    }


def _as_string_list(value: Any) -> list[str]:
    """Normalize a scalar or sequence parameter into a string list."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value] if value.strip() else []
    if isinstance(value, (list, tuple, set)):
        return [str(item) for item in value if str(item).strip()]
    return [str(value)]


__all__ = [
    "DesignCodeGenerationAgent",
    "build_design_code_generation_constraints",
    "build_design_code_generation_prompt",
]
