from typing import Any, AsyncGenerator
from typing_extensions import override
import asyncio

from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event
from pydantic import BaseModel, Field, field_validator, model_validator
from src.logger import logger
from src.agents.experts.base import CreativeExpert
from src.agents.experts.image_generation import tool as generation_tools
from src.agents.experts.schema_utils import as_prompt_list, clean_string, current_output_dict
from src.runtime.workspace import build_workspace_file_record, save_binary_output


def _parse_optional_bool(value) -> bool | None:
    """Return a bool for explicit values and None when the parameter is absent."""
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on"}


def _parse_bool(value, *, default: bool = False) -> bool:
    """Return a bool for flexible user-provided values."""
    parsed = _parse_optional_bool(value)
    return default if parsed is None else parsed


class ImageGenerationParameters(BaseModel):
    """Structured request contract read from ``current_parameters``."""

    prompts: list[str] = Field(default_factory=list)
    provider: str = "nano_banana"
    aspect_ratio: str = "16:9"
    resolution: str = "1K"
    gpt_image_size: str = "1024x1024"
    gpt_image_quality: str = "high"
    dashscope_model_name: str = ""
    dashscope_size: str = ""
    dashscope_negative_prompt: str = ""
    dashscope_prompt_extend: bool | None = None
    dashscope_watermark: bool = False
    dashscope_thinking_mode: bool | None = None

    @model_validator(mode="before")
    @classmethod
    def _coerce_mapping(cls, value: Any) -> dict[str, Any]:
        if not isinstance(value, dict):
            return {}
        return {
            "prompts": value.get("prompt"),
            "provider": value.get("provider", "nano_banana"),
            "aspect_ratio": value.get("aspect_ratio", "16:9"),
            "resolution": value.get("resolution", "1K"),
            "gpt_image_size": value.get("size", "1024x1024"),
            "gpt_image_quality": value.get("quality", "high"),
            "dashscope_model_name": generation_tools.normalize_dashscope_image_model_name(
                value.get("model_name")
            ),
            "dashscope_size": value.get("size", ""),
            "dashscope_negative_prompt": value.get("negative_prompt", ""),
            "dashscope_prompt_extend": _parse_optional_bool(value.get("prompt_extend")),
            "dashscope_watermark": _parse_bool(value.get("watermark"), default=False),
            "dashscope_thinking_mode": _parse_optional_bool(value.get("thinking_mode")),
        }

    @field_validator("prompts", mode="before")
    @classmethod
    def _normalize_prompts(cls, value: Any) -> list[str]:
        return as_prompt_list(value)

    @field_validator(
        "provider",
        "aspect_ratio",
        "resolution",
        "gpt_image_size",
        "gpt_image_quality",
        "dashscope_model_name",
        "dashscope_size",
        "dashscope_negative_prompt",
        mode="before",
    )
    @classmethod
    def _strip_string(cls, value: Any) -> str:
        return clean_string(value)

    @field_validator("provider")
    @classmethod
    def _normalize_provider(cls, value: str) -> str:
        return value.lower() or "nano_banana"


class ImageGenerationOutput(BaseModel):
    """Structured ``current_output`` contract emitted by ``ImageGenerationAgent``."""

    status: str
    message: str
    output_files: list[dict[str, Any]] | None = None

    @field_validator("status", mode="before")
    @classmethod
    def _normalize_status(cls, value: Any) -> str:
        return clean_string(value).lower() or "error"

    @field_validator("message", mode="before")
    @classmethod
    def _strip_message(cls, value: Any) -> str:
        return clean_string(value)

    def to_current_output(self) -> dict[str, Any]:
        """Return the stable dictionary payload stored in ADK session state."""
        return current_output_dict(self)


class ImageGenerationAgent(CreativeExpert):
    """A custom agent that orchestrates a sequence of agents to generate an image from text."""

    def __init__(
        self,
        name: str,
        description: str = "",
    ) -> None:
        """Initializes the Text2ImageAgent."""
        super().__init__(
            name=name,
            sub_agents=[],
            description=description,
        )

    @override
    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """
        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """
        
        raw_parameters = ctx.session.state.get('current_parameters', {})
        has_prompt_key = isinstance(raw_parameters, dict) and "prompt" in raw_parameters
        current_parameters = ImageGenerationParameters.model_validate(raw_parameters)
        if not has_prompt_key:
            error_text = f"Missing parameters provided to {self.name}, must include: prompt"
            current_output = ImageGenerationOutput(status="error", message=error_text).to_current_output()
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output":current_output})
            return

        original_prompt = current_parameters.prompts
        provider = current_parameters.provider

        # prompt enhancement
        tasks = [generation_tools.prompt_enhancement_tool(ctx, prompt) for prompt in original_prompt]
        result_list = await asyncio.gather(*tasks)
        prompt_list = []
        for i, result in enumerate(result_list):
            if result['status'] == 'success':
                prompt_list.append(result['message'])
            else:
                logger.warning(f"{self.name}: prompt enhance failed, use original prompt")
                prompt_list.append(original_prompt[i])

        if provider == "seedream":
            tasks = [generation_tools.seedream_image_generation_tool(prompt) for prompt in prompt_list]
        elif provider == "gpt_image":
            tasks = [
                generation_tools.gpt_image_generation(
                    prompt,
                    generation_tools.API_CONFIG.OPENAI_API_KEY or "",
                    size=current_parameters.gpt_image_size,
                    quality=current_parameters.gpt_image_quality,
                )
                for prompt in prompt_list
            ]
        elif provider == "dashscope":
            tasks = [
                generation_tools.dashscope_image_generation(
                    prompt,
                    model_name=current_parameters.dashscope_model_name,
                    size=current_parameters.dashscope_size,
                    resolution=current_parameters.resolution,
                    negative_prompt=current_parameters.dashscope_negative_prompt,
                    prompt_extend=current_parameters.dashscope_prompt_extend,
                    watermark=current_parameters.dashscope_watermark,
                    thinking_mode=current_parameters.dashscope_thinking_mode,
                )
                for prompt in prompt_list
            ]
        else:
            tasks = [
                generation_tools.nano_banana_image_generation_tool(
                    ctx,
                    prompt,
                    aspect_ratio=current_parameters.aspect_ratio,
                    resolution=current_parameters.resolution,
                )
                for prompt in prompt_list
            ]
        result_list = await asyncio.gather(*tasks)

        current_turn = int(ctx.session.state.get("turn_index", 0) or 0)
        current_step = int(ctx.session.state.get("step", 0) or 0)
        current_expert_step = int(ctx.session.state.get("expert_step", 0) or 0)
        output_artifacts = []
        message = []
        for i, (prompt, result) in enumerate(zip(prompt_list, result_list)):
            result_status = result["status"] if isinstance(result, dict) else result.status
            result_message = result["message"] if isinstance(result, dict) else result.message
            result_provider = result.get("provider", provider) if isinstance(result, dict) else result.provider
            if result_status == 'error':
                message.append(f"image generation task{i+1} failed: {result_message}")
            else:
                output_path = save_binary_output(
                    result_message,
                    session_id=ctx.session.id,
                    turn_index=current_turn,
                    step=current_step,
                    output_type="generation",
                    index=i,
                    extension=".png",
                )
                artifact_name = output_path.name
                message.append(
                    f"image generation task{i+1} success, output file: {artifact_name}"
                )

                provider_name = result_provider
                description = (
                    f"The {i+1}th image generated by image generation tool in "
                    f"turn {current_turn}, step {current_step}, provider is {provider_name}, prompt is {prompt}"
                )
                output_artifacts.append(
                    build_workspace_file_record(
                        output_path,
                        description=description,
                        source="expert",
                        name=artifact_name,
                        turn=current_turn,
                        step=current_step,
                        expert_step=current_expert_step,
                    )
                )
        
        if len(output_artifacts)==0:
            message = f"{self.name} all {len(result_list)} image generation tasks failed: {','.join(message)}"
            logger.error(message)
            current_output = ImageGenerationOutput(status="error", message=message).to_current_output()
            
        else:
            message = f"{self.name} has completed {len(result_list)} image generation tasks: {','.join(message)}"
            logger.info(message)
            current_output = ImageGenerationOutput(
                status="success",
                message=message,
                output_files=output_artifacts,
            ).to_current_output()

        yield self.format_event(message, {"current_output":current_output})
        return


__all__ = [
    "ImageGenerationAgent",
    "ImageGenerationOutput",
    "ImageGenerationParameters",
]
