"""Public schema contracts for the PPT product line."""

from src.productions.ppt.schemas.contracts import (
    REQUIRED_DECK_PAGE_TYPES,
    ConfirmedRequirement,
    DeckChapter,
    DeckContentPlan,
    DeckPageAsset,
    DeckPagePlan,
    DeliveryManifest,
    EditabilityRequirement,
    HtmlRouteBuildPackage,
    HtmlTemplatePackage,
    PptProductResult,
    QualityReviewResult,
    ReferenceAsset,
    SlideCountPolicy,
    SourceInput,
    SourceUnderstanding,
    StyleRequirement,
    TemplateRequirement,
    validate_deck_content_plan,
)

__all__ = [
    "REQUIRED_DECK_PAGE_TYPES",
    "ConfirmedRequirement",
    "DeckChapter",
    "DeckContentPlan",
    "DeckPageAsset",
    "DeckPagePlan",
    "DeliveryManifest",
    "EditabilityRequirement",
    "HtmlRouteBuildPackage",
    "HtmlTemplatePackage",
    "PptProductResult",
    "QualityReviewResult",
    "ReferenceAsset",
    "SlideCountPolicy",
    "SourceInput",
    "SourceUnderstanding",
    "StyleRequirement",
    "TemplateRequirement",
    "validate_deck_content_plan",
]
