"""PageProductManager-private code generation agent."""

from __future__ import annotations

from typing import Any, AsyncGenerator

from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event
from typing_extensions import override

from src.agents.experts.base import CreativeExpert
from src.runtime.code_artifacts import generate_code_artifact


class PageCodeGenerationAgent(CreativeExpert):
    """Generate content-first HTML page artifacts."""

    def __init__(self, name: str = "PageCodeGenerationAgent", description: str = "") -> None:
        """Initialize the private page code generation agent."""
        super().__init__(name=name, description=description)

    async def run_generation(
        self,
        runtime_context: Any,
        *,
        prompt: str,
        language: str = "html",
        output_path: str = "",
        context_files: list[str] | None = None,
        constraints: list[str] | None = None,
    ) -> dict[str, Any]:
        """Generate one content-first page artifact file through the shared code runtime."""
        clean_prompt = str(prompt or "").strip()
        if not clean_prompt:
            return _build_current_output(
                {
                    "status": "error",
                    "message": f"Missing parameters provided to {self.name}, must include: prompt",
                    "error_type": "invalid_parameters",
                    "retryable": False,
                    "raw_error_summary": "missing prompt",
                    "output_files": [],
                    "language": language,
                }
            )

        result = await generate_code_artifact(
            runtime_context,
            prompt=build_page_code_generation_prompt(clean_prompt),
            language=str(language or "html").strip() or "html",
            output_path=str(output_path or "").strip(),
            context_files=context_files or [],
            constraints=build_page_code_generation_constraints(constraints or []),
            output_type="page_code_generation",
            output_description="Page artifact generated by PageCodeGenerationAgent.",
            output_source="page_code_generation_agent",
        )
        return _build_current_output(result)

    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Run one page code generation request from ADK session parameters."""
        current_parameters = dict(ctx.session.state.get("current_parameters", {}) or {})
        current_output = await self.run_generation(
            ctx,
            prompt=str(current_parameters.get("prompt", "")).strip(),
            language=str(current_parameters.get("language", "html")).strip() or "html",
            output_path=str(current_parameters.get("output_path", "")).strip(),
            context_files=_as_string_list(current_parameters.get("context_files")),
            constraints=_as_string_list(current_parameters.get("constraints")),
        )
        yield self.format_event(
            current_output.get("message", ""),
            {
                "current_output": current_output,
                "page_code_generation_results": current_output,
            },
        )


def build_page_code_generation_prompt(user_prompt: str) -> str:
    """Return a content-first HTML page generation brief."""
    return "\n".join(
        [
            "# Creative Claw Page Artifact Mode",
            "",
            "You are generating a content-first HTML page for a poster, long image, visual article, social post, or marketing one-pager.",
            "The medium is the message and reading experience. Prioritize copy, narrative sequence, image placement, platform fit, and final readability.",
            "",
            "## Page Product Posture",
            "- Treat HTML as a publishing and layout container, not as an app shell or product UI prototype.",
            "- Adapt the reading rhythm to the requested platform, such as 公众号, 小红书, 朋友圈长图, social post, or marketing poster.",
            "- Build one immediately readable page. Do not create dashboards, multi-screen prototypes, interactive product flows, or style-comparison boards.",
            "- The user cares most about the words, content structure, visual story, and images. Keep layout supportive and straightforward.",
            "- Good outputs should feel like a finished social/marketing page, not a generic website template.",
            "",
            "## Content First",
            "- Preserve the supplied copy exactly when the brief marks it as final.",
            "- If copy is missing, write concise useful draft copy that fits the requested platform and mark assumptions in comments only when necessary.",
            "- Make headline, opening hook, body sections, CTA, and footer easy to scan.",
            "- Prefer real paragraphs, lists, captions, quote blocks, and callouts over decorative filler cards.",
            "- Do not invent fake data, fake testimonials, fake legal claims, or unsupported performance numbers.",
            "",
            "## Image And Asset Rules",
            "- Use provided workspace-relative image paths exactly as given.",
            "- Search-sourced images are references unless explicitly approved for direct final use.",
            "- Put all readable text in HTML/CSS, not baked into generated images, unless the user explicitly asks otherwise.",
            "- Every final image should have alt text and a clear content role.",
            "",
            "## HTML Output Contract",
            "- Generate exactly one complete standalone HTML file.",
            "- Use inline CSS and minimal inline JavaScript only when needed.",
            "- The file must run locally without a backend or build step.",
            "- Avoid external network assets unless the prompt explicitly approves them.",
            "- Avoid local absolute filesystem paths.",
            "- Keep the page width, spacing, and type scale responsive enough for desktop preview and mobile screenshot capture.",
            "- For long-image style work, make the page vertically continuous with predictable sections and no hidden content.",
            "- Use semantic HTML and readable class names so future edits can target content blocks easily.",
            "",
            "## Quality Check",
            "- Before finalizing, silently check: content completeness, reading order, image/copy alignment, platform fit, and local-file safety.",
            "- Fix the weakest point before returning the file.",
            "",
            "# User Page Brief",
            user_prompt.strip(),
        ]
    )


def build_page_code_generation_constraints(extra_constraints: list[str]) -> list[str]:
    """Return default page code generation constraints plus caller constraints."""
    defaults = [
        "Return only the complete file contents.",
        "Generate exactly one standalone HTML file.",
        "Optimize for content-first communication: copy, narrative sequence, images, and CTA.",
        "Use HTML/CSS text for readable copy; do not bake text into images unless explicitly requested.",
        "Support poster and long-image style compositions with responsive width constraints.",
        "Use workspace-relative asset paths exactly as provided.",
        "Do not include local absolute filesystem paths.",
        "Do not rely on external network assets unless explicitly approved.",
    ]
    return defaults + [str(item) for item in extra_constraints if str(item).strip()]


def _build_current_output(result: dict[str, Any]) -> dict[str, Any]:
    """Normalize a generation result into the private agent output contract."""
    message = str(result.get("message", "") or "").strip()
    status = str(result.get("status", "error") or "error").strip().lower()
    return {
        "status": status,
        "message": message,
        "output_text": message if status == "success" else "",
        "output_files": list(result.get("output_files") or []),
        "error_type": str(result.get("error_type", "") or "").strip(),
        "retryable": bool(result.get("retryable", False)),
        "raw_error_summary": str(result.get("raw_error_summary", "") or "").strip(),
        "output_path": str(result.get("output_path", "") or "").strip(),
        "language": str(result.get("language", "") or "").strip(),
        "warnings": list(result.get("warnings") or []),
    }


def _as_string_list(value: Any) -> list[str]:
    """Normalize a scalar or sequence value into a list of strings."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value] if value.strip() else []
    if isinstance(value, list):
        return [str(item) for item in value if str(item).strip()]
    return [str(value)] if str(value).strip() else []


__all__ = [
    "PageCodeGenerationAgent",
    "build_page_code_generation_constraints",
    "build_page_code_generation_prompt",
]
