"""PageProductManager-private code generation agent."""

from __future__ import annotations

from typing import Any, AsyncGenerator

from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event
from typing_extensions import override

from src.agents.experts.base import CreativeExpert
from src.logger import logger
from src.productions.page.page_product_manager.templates import select_page_template_match
from src.runtime.code_artifacts import generate_code_artifact


class PageCodeGenerationAgent(CreativeExpert):
    """Generate content-first HTML page artifacts."""

    def __init__(self, name: str = "PageCodeGenerationAgent", description: str = "") -> None:
        """Initialize the private page code generation agent."""
        super().__init__(name=name, description=description)

    async def run_generation(
        self,
        runtime_context: Any,
        *,
        prompt: str,
        language: str = "html",
        output_path: str = "",
        context_files: list[str] | None = None,
        constraints: list[str] | None = None,
        template_id: str = "",
        allow_auto_template: bool = True,
    ) -> dict[str, Any]:
        """Generate one content-first page artifact file through the shared code runtime."""
        clean_prompt = str(prompt or "").strip()
        if not clean_prompt:
            return _build_current_output(
                {
                    "status": "error",
                    "message": f"Missing parameters provided to {self.name}, must include: prompt",
                    "error_type": "invalid_parameters",
                    "retryable": False,
                    "raw_error_summary": "missing prompt",
                    "output_files": [],
                    "language": language,
                }
            )

        result = await generate_code_artifact(
            runtime_context,
            prompt=build_page_code_generation_prompt(
                clean_prompt,
                template_id=str(template_id or "").strip(),
                allow_auto_template=allow_auto_template,
            ),
            language=str(language or "html").strip() or "html",
            output_path=str(output_path or "").strip(),
            context_files=context_files or [],
            constraints=build_page_code_generation_constraints(constraints or []),
            output_type="page_code_generation",
            output_description="Page artifact generated by PageCodeGenerationAgent.",
            output_source="page_code_generation_agent",
        )
        return _build_current_output(result)

    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Run one page code generation request from ADK session parameters."""
        current_parameters = dict(ctx.session.state.get("current_parameters", {}) or {})
        current_output = await self.run_generation(
            ctx,
            prompt=str(current_parameters.get("prompt", "")).strip(),
            language=str(current_parameters.get("language", "html")).strip() or "html",
            output_path=str(current_parameters.get("output_path", "")).strip(),
            context_files=_as_string_list(current_parameters.get("context_files")),
            constraints=_as_string_list(current_parameters.get("constraints")),
            template_id=str(current_parameters.get("template_id", "")).strip(),
            allow_auto_template=_as_bool(current_parameters.get("allow_auto_template"), default=True),
        )
        yield self.format_event(
            current_output.get("message", ""),
            {
                "current_output": current_output,
                "page_code_generation_results": current_output,
            },
        )


def build_page_code_generation_prompt(
    user_prompt: str,
    template_id: str = "",
    *,
    allow_auto_template: bool = True,
) -> str:
    """Return a content-first HTML page generation brief."""
    clean_template_id = str(template_id or "").strip()
    template_match = (
        select_page_template_match(user_prompt, template_id=clean_template_id)
        if clean_template_id or allow_auto_template
        else None
    )
    selected_template = template_match.template if template_match is not None else None
    if selected_template is None:
        template_prompt_block = "\n".join(
            [
                "No built-in Page template was selected.",
                "Generate freely from the user brief while following the Page artifact rules above.",
                "Do not mention template selection or the absence of a template in the generated page.",
            ]
        )
        template_score = 0
        template_reasons = (
            list(template_match.reasons)
            if template_match is not None
            else ["Template auto-selection was disabled by the Page pipeline."]
        )
    else:
        template_prompt_block = selected_template.to_prompt_block()
        template_score = template_match.score if template_match is not None else 0
        template_reasons = list(template_match.reasons) if template_match is not None else []
    logger.info(
        "Page code generation template selection: use_template={} template_id={} score={} allow_auto_template={} reasons={}",
        selected_template is not None,
        selected_template.id if selected_template is not None else "",
        template_score,
        allow_auto_template,
        template_reasons,
    )
    return "\n".join(
        [
            "# Creative Claw Page Artifact Mode",
            "",
            "You are generating a content-first HTML page for a poster, long image, visual article, social post, or marketing one-pager.",
            "The medium is the message and reading experience. Prioritize copy, narrative sequence, image placement, platform fit, and final readability.",
            "",
            "## Page Product Posture",
            "- Treat HTML as a publishing and layout container, not as an app shell or product UI prototype.",
            "- Adapt the reading rhythm to the requested platform, such as 公众号, 小红书, 朋友圈长图, social post, or marketing poster.",
            "- Build one immediately readable page. Do not create dashboards, multi-screen prototypes, interactive product flows, or style-comparison boards.",
            "- For poster requests, build one finished publishable poster by default. Do not deliver a multi-option review board unless the user explicitly requested option comparison.",
            "- The user cares most about the words, content structure, visual story, and images. Keep layout supportive and straightforward.",
            "- Good outputs should feel like a finished social/marketing page, not a generic website template.",
            "",
            "## Content First",
            "- Preserve the supplied copy exactly when the brief marks it as final.",
            "- If copy is missing, write concise useful draft copy that fits the requested platform and mark assumptions in comments only when necessary.",
            "- Make headline, opening hook, body sections, CTA, and footer easy to scan.",
            "- Prefer real paragraphs, lists, captions, quote blocks, and callouts over decorative filler cards.",
            "- Do not invent fake data, fake testimonials, fake legal claims, or unsupported performance numbers.",
            "- If the input includes structured data such as CSV, JSON, or tables, extract grounded insights and render them as charts, tables, or concise callouts.",
            "- For Chinese/English mixed copy, keep readable spacing between CJK and Latin text.",
            "",
            "## Poster And Long Image Visual Rules",
            "- Decide the target artboard before styling. For poster briefs, prefer a fixed 1080-width artboard such as 1080x1920, 1080x1350, or the exact user-specified size.",
            "- Make the first viewport carry the strongest visual message: one clear hero subject, one dominant headline, and one readable next action or memory point.",
            "- Use a deliberate grid, shared alignment lines, safe margins, and a visible type scale. The headline, secondary copy, body, notes, and CTA must not look equal in weight.",
            "- Use imagery as composition, not decoration. Preserve the hero subject, reserve clean space for HTML text, and avoid covering important image content with dense cards.",
            "- If the brief contains too much detail for one poster, turn secondary content into a disciplined long-image flow instead of squeezing everything into one crowded frame.",
            "- Avoid generic card stacks, dashboard-like panels, landing-page sections, and visual comparison canvases for final poster delivery.",
            "",
            "## Image And Asset Rules",
            "- If the brief lists a non-empty `html_relative_src`, use that relative path exactly for image `src` attributes and CSS `url(...)` references.",
            "- Do not use `absolute_file_src` when `html_relative_src` is present; `file://` images are blocked in CreativeClaw's HTTP design tab.",
            "- If a material only has a workspace-relative image path, use that path exactly as given.",
            "- Search-sourced images are references unless explicitly approved for direct final use.",
            "- Put all readable text in HTML/CSS, not baked into generated images, unless the user explicitly asks otherwise.",
            "- Every final image should have alt text and a clear content role.",
            "",
            "## HTML Output Contract",
            "- Return only the complete standalone HTML file contents. Do not wrap the answer in markdown fences and do not add any explanatory text before or after the file.",
            "- The document must start with `<!DOCTYPE html>` and end with `</html>`.",
            "- Generate exactly one complete standalone HTML file.",
            "- Prefer inline CSS and minimal inline JavaScript only when needed.",
            "- The file must run locally without a backend or build step.",
            "- Do not assume external network access. Use external CDN assets such as Tailwind Play, Google Fonts, jsDelivr scripts, or remote images only when the prompt explicitly approves them.",
            "- Prefer HTML-relative local asset paths supplied by the brief so the page works in Finder and CreativeClaw's local HTTP preview.",
            "- Do not invent local absolute paths or `file://` URLs.",
            "- Do not describe file-writing steps. The Creative Claw runtime writes the returned file contents to the intended output path.",
            "- Keep the page width, spacing, and type scale responsive enough for desktop preview and mobile screenshot capture.",
            "- For long-image style work, make the page vertically continuous with predictable sections and no hidden content.",
            "- Use semantic HTML and readable class names so future edits can target content blocks easily.",
            "",
            "## Visual Quality Defaults",
            "- Use a clear type hierarchy, deliberate grid, safe margins, and readable line lengths.",
            "- Prefer Noto Sans SC or Noto Serif SC for Chinese copy, and Inter, Manrope, or system UI fonts for English copy.",
            "- Use one primary color, two neutral colors, and at most one accent color unless the selected skill or user brief requires a stronger style.",
            "- Avoid pure `#000` and `#fff` unless the visual style specifically needs hard black and white; prefer near-black and near-white tones.",
            "- Keep contrast strong enough for important text and calls to action.",
            "- Use motion sparingly and only when it improves comprehension or perceived polish.",
            "- Template-specific or skill-specific style rules override these defaults.",
            "",
            "## Selected Built-In Page Template",
            "When a built-in Page template is selected, use it as the page's structural and visual direction. Explicit user requirements, real source content, and safety constraints still take priority.",
            "Do not mention the template name, template id, or selection logic in the generated page.",
            template_prompt_block,
            "",
            "## Quality Check",
            "- Before finalizing, silently check: content completeness, reading order, image/copy alignment, platform fit, and local-file safety.",
            "- For poster work, also check: final vs review-board mode, first-eye focus, safe margins, type hierarchy, CTA clarity, text overflow, and whether the hero image still reads.",
            "- Fix the weakest point before returning the file.",
            "",
            "# User Page Brief",
            user_prompt.strip(),
        ]
    )


def build_page_code_generation_constraints(extra_constraints: list[str]) -> list[str]:
    """Return default page code generation constraints plus caller constraints."""
    defaults = [
        "Return only the complete file contents.",
        "Do not wrap the answer in markdown fences or add explanatory text before or after the HTML.",
        "The HTML document must start with <!DOCTYPE html> and end with </html>.",
        "Generate exactly one standalone HTML file.",
        "Optimize for content-first communication: copy, narrative sequence, images, and CTA.",
        "Do not invent fake data, testimonials, legal claims, prices, metrics, or unsupported performance numbers.",
        "If user input contains structured data, render grounded insights as charts, tables, or concise callouts.",
        "Use HTML/CSS text for readable copy; do not bake text into images unless explicitly requested.",
        "Support poster and long-image style compositions with responsive width constraints.",
        "For poster requests, generate one finished publishable artboard by default, not a multi-option review board.",
        "For poster artboards, use clear safe margins, type hierarchy, one hero subject, and an explicit CTA or memory point.",
        "Use non-empty html_relative_src material paths exactly when provided.",
        "Do not use file:// URLs when html_relative_src is available.",
        "Do not invent local absolute paths or file:// URLs.",
        "Do not rely on external network assets or CDN resources unless explicitly approved.",
        "When a built-in Page template is selected, use it as structural and visual guidance unless explicit user requirements override it.",
        "Treat visual quality rules as defaults that can be overridden by a selected skill or explicit user style brief.",
    ]
    return defaults + [str(item) for item in extra_constraints if str(item).strip()]


def _build_current_output(result: dict[str, Any]) -> dict[str, Any]:
    """Normalize a generation result into the private agent output contract."""
    message = str(result.get("message", "") or "").strip()
    status = str(result.get("status", "error") or "error").strip().lower()
    return {
        "status": status,
        "message": message,
        "output_text": message if status == "success" else "",
        "output_files": list(result.get("output_files") or []),
        "error_type": str(result.get("error_type", "") or "").strip(),
        "retryable": bool(result.get("retryable", False)),
        "raw_error_summary": str(result.get("raw_error_summary", "") or "").strip(),
        "output_path": str(result.get("output_path", "") or "").strip(),
        "language": str(result.get("language", "") or "").strip(),
        "warnings": list(result.get("warnings") or []),
    }


def _as_string_list(value: Any) -> list[str]:
    """Normalize a scalar or sequence value into a list of strings."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value] if value.strip() else []
    if isinstance(value, list):
        return [str(item) for item in value if str(item).strip()]
    return [str(value)] if str(value).strip() else []


def _as_bool(value: Any, *, default: bool) -> bool:
    """Normalize a JSON-like boolean value."""
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in {"false", "0", "no", "off"}:
            return False
        if normalized in {"true", "1", "yes", "on"}:
            return True
    return bool(value)


__all__ = [
    "PageCodeGenerationAgent",
    "build_page_code_generation_constraints",
    "build_page_code_generation_prompt",
]
