"""Tool helpers for reusable code generation."""

from __future__ import annotations

from typing import Any

from google.adk.agents.invocation_context import InvocationContext

from src.runtime.code_artifacts import (
    generate_code_artifact,
    normalize_code_language,
    strip_code_fence,
)


async def code_generation_tool(
    ctx: InvocationContext,
    *,
    prompt: str,
    language: str = "html",
    output_path: str = "",
    context_files: list[str] | None = None,
    constraints: list[str] | None = None,
) -> dict[str, Any]:
    """Generate one code file with the configured LLM and write it to workspace."""
    return await generate_code_artifact(
        ctx,
        prompt=prompt,
        language=language,
        output_path=output_path,
        context_files=context_files,
        constraints=constraints,
        output_type="code_generation",
        output_description=f"Code generated by CodeGenerationExpert ({normalize_code_language(language)}).",
        output_source="expert",
    )
