from typing import Any, AsyncGenerator
from typing_extensions import override

from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event
from google.adk.tools import ToolContext
from pydantic import BaseModel, Field, model_validator
from src.logger import logger

from src.agents.experts.base import CreativeExpert
from src.agents.experts.schema_utils import current_output_dict
from src.agents.experts.search.tool import retrieve_image_by_text, DDGS_search
from src.runtime.workspace import build_workspace_file_record, save_binary_output


class SearchParameters(BaseModel):
    """Structured request contract read from ``current_parameters``."""

    query: Any = None
    mode: Any = None
    count: Any = 5

    @model_validator(mode="before")
    @classmethod
    def _coerce_mapping(cls, value: Any) -> dict[str, Any]:
        if not isinstance(value, dict):
            return {}
        return {
            "query": value.get("query"),
            "mode": value.get("mode"),
            "count": value.get("count", 5),
        }

    @property
    def normalized_mode(self) -> str:
        """Return the mode used by the existing search branch logic."""
        mode = self.mode
        if mode not in {"image", "text", "all"}:
            return "all"
        return str(mode)

    @property
    def has_valid_mode(self) -> bool:
        """Whether the requested mode is one of the supported branch names."""
        return self.mode in {"image", "text", "all"}


class SearchOutput(BaseModel):
    """Structured ``current_output`` contract emitted by ``SearchAgent``."""

    status: str
    message: str
    output_files: list[dict[str, Any]] | None = Field(default=None)

    @model_validator(mode="before")
    @classmethod
    def _coerce_output(cls, value: Any) -> dict[str, Any]:
        if not isinstance(value, dict):
            return {"status": "error", "message": str(value)}
        return value

    def to_current_output(self) -> dict[str, Any]:
        """Return the stable dictionary payload stored in ADK session state."""
        return current_output_dict(self)


def _parse_search_parameters(raw_parameters: Any) -> SearchParameters:
    return SearchParameters.model_validate(raw_parameters)


class SearchAgent(CreativeExpert):
    """
    a custom agent for search image or text
    """

    def __init__(
        self,
        name: str,
        description: str = ""
    ) :
        super().__init__(
            name = name,
            description = description
        )

    @override
    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """Runs the SearchAgent asynchronously.

        This method achieves retrieve or download images.

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """
        raw_parameters = ctx.session.state.get('current_parameters', {})

        if not isinstance(raw_parameters, dict) or ('query' not in raw_parameters) or ('mode' not in raw_parameters):
            error_text = f"Missing parameters provided to {self.name}, must include: query, mode"
            current_output = SearchOutput(status="error", message=error_text).to_current_output()
            logger.error(error_text)

            yield self.format_event(error_text, {"current_output":current_output})

            return

        current_parameters = _parse_search_parameters(raw_parameters)

        if not current_parameters.has_valid_mode:
            logger.warning(f"SearchAgent got invalid parameters: mode: {current_parameters.mode}, set to 'all'")
            raw_parameters['mode'] = current_parameters.normalized_mode

        mode = current_parameters.normalized_mode
        logger.info(f"[{self.name}] start searching. mode: {mode}, query: {current_parameters.query}")
        # output binary file   
        if mode == 'image':
            current_output = SearchOutput.model_validate(await self.search_image(ctx)).to_current_output()
            yield self.format_event(current_output['message'], {"current_output":current_output})
            return
        
        if mode == 'text':
            current_output = SearchOutput.model_validate(await self.search_text(ctx)).to_current_output()
            yield self.format_event(current_output['message'], {"current_output":current_output})
            return
        
        if mode == 'all':
            image_output = await self.search_image(ctx)
            text_output = await self.search_text(ctx)

            if image_output['status'] == 'error' and text_output['status'] == 'error':
                error_text = '\n'.join([image_output['message'], text_output['message']])
                current_output = SearchOutput(status="error", message=error_text).to_current_output()
                yield self.format_event(error_text, {"current_output":current_output})
            
            else:
                text = '\n'.join([image_output['message'], text_output['message']])
                output_files = None
                if image_output['status']=='success' and 'output_files' in image_output:
                    output_files = image_output['output_files']

                # text_output(search result) is usually very long, so it is not included in message to avoid too long text displayed for user.
                message = image_output['message']
                if text_output['status']=='success':
                    message += f"\n{self.name} has competed text retrieval."
                else:
                    message += f"\n{text_output['message']}"

                current_output = SearchOutput(
                    status="success",
                    message=message,
                    output_files=output_files,
                ).to_current_output()
                
                yield self.format_event(text, {"current_output":current_output})
                
            return
        
        
    async def search_image(self, ctx: InvocationContext):
        rsp = await retrieve_image_by_text(ToolContext(ctx))

        if rsp["status"] == "error":
            error_text = f"{self.name} image retrieval failed: {rsp['message']}"
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)
            return current_output
        else:
            # save image:
            current_turn = int(ctx.session.state.get("turn_index", 0) or 0)
            current_step = int(ctx.session.state.get("step", 0) or 0)
            current_expert_step = int(ctx.session.state.get("expert_step", 0) or 0)
            output_files = []
            for i, img_binary in enumerate(rsp['message']):
                output_path = save_binary_output(
                    img_binary,
                    session_id=ctx.session.id,
                    turn_index=current_turn,
                    step=current_step,
                    output_type="search",
                    index=i,
                    extension=".png",
                )
                artifact_name = output_path.name

                output_files.append(
                    build_workspace_file_record(
                        output_path,
                        description=f"The search result of {self.name} based on query: {ctx.session.state['current_parameters']['query']}",
                        source="expert",
                        name=artifact_name,
                        turn=current_turn,
                        step=current_step,
                        expert_step=current_expert_step,
                    )
                )

            # Emit the result event.
            text = f"{self.name} has completed image searching with {len(rsp['message'])} results. The image name of results: {[','.join(file_info['name'] for file_info in output_files)]}"

            current_output = SearchOutput(
                status="success",
                message=text,
                output_files=output_files,
            ).to_current_output()
            
            return current_output
        
    async def search_text(self, ctx: InvocationContext):
        rsp = await DDGS_search(ToolContext(ctx))

        if rsp['status'] == 'error':
            error_text = f"{self.name} text searching failed: {rsp['message']}"
            current_output = {"status": "error", "message": error_text}
            logger.error(error_text)
            return current_output
        else:
            text = f"{self.name} has completed text searching, result:\n{rsp['message']}"
            current_output = SearchOutput(status="success", message=text).to_current_output()
            return current_output


__all__ = ["SearchAgent", "SearchOutput", "SearchParameters"]
